version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 10
    labels: ["dependencies"]

    ignore:
      - dependency-name: "clang"
        versions: [">=18.1.9"]

    groups:
      python-minor-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels: ["dependencies"]
    groups:
      actions-minor-patch:
        update-types: ["minor", "patch"]
