#[build-system]
#requires = ["hatchling"]
#build-backend = "hatchling.build"

[project]
name = "renaissance"
version = "0.0.1"
description = "Renaissance reimplementation in Python"
readme = "README.md"
authors = [
    { name = "Pierre van de Laar", email = "pierre.vandelaar@tno.nl" },
    { name = "Jinmin Hu", email = "jinmin.hu@capgemini.com" },
    { name = "Luna Li", email = "luna.li@capgemini.com" }
]
license = { text = "EPL-2.0" }
requires-python = "==3.14.*"
dependencies = [
    "textx==4.3.0",
    "dataclasses-json==0.6.7",
    "pyperclip>=1.8",
    "clang==18.1.8",
    "libclang==18.1.1",
    "more-itertools>=10.0",
    "networkx>=3.0",
    "pyhamcrest>=2.1",
    "pyecore>=0.14",
    "pyyaml>=6.0",
    "termcolor>=2.0",
    "typing-extensions>=4.0",
    "tree-sitter>=0.25",
    "tree-sitter-python==0.25.0",
    "tree-sitter-cpp==0.23.4",
    "tree-sitter-java==0.23.5",
    "ast-comments>=1.0",
    "libcst>=1.8.6",
    "antlr4-python3-runtime>=4.13.2",
    "hypothesmith>=0.3.3",
]

[dependency-groups]
test = [
    "hypothesis>=6.152.4",
    "hypothesmith>=0.3.3",
    "parameterized>=0.9",
    "pytest>=8.0",
    "pytest-bdd==8.1.0",
    "pytest-cov>=7.0",
    "pytest-mock>=3.15",
    "pytest-profiling>=1.8",
    "coverage>=7.0",
    "behave"
]
lint = [
    "ruff>=0.5",
    "autopep8>=2.0",
    "codespell>=2.4",
]
dev = [
    {include-group = "test"},
    {include-group = "lint"},
    {include-group = "docs"},
]
docs = [
    "mkdocs>=1.6",
    "mkdocs-material>=9.0",
    "mkdocstrings[python]>=0.25",
    "mkdocs-autorefs>=1.0",
    "mkdocs-exporter>=6.0",
]

[project.urls]
Homepage = "https://github.com/TNO/Renaissance-Experiments"
Issues = "https://github.com/TNO/Renaissance-Experiments/issues"

[project.scripts]
rejuvenate = "rejuvenation.cli:refactor"
taut2test = "rejuvenation.cli:refactor"

[tool.pytest.ini_options]
testpaths = ["test", "features"]
pythonpath = ["src", "test", "features"]

[tool.coverage.run]
source = ["src"]
omit = ["test/*", "features/*"]

[tool.coverage.report]
show_missing = true
skip_covered = false

[tool.ruff]
line-length = 120
src = ["src", "test", "features"]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "N", "D", "UP"]

