"""AI: Mapping of Python `ast` node kinds and operators to the library's semantic kinds."""

from renaissance.syntax_tree.semantic_kind import SemanticKind

PYTHON_OPERATOR_MAP = {
    "AnnAssign": "=",
    "Assert": "assert",
    "Assign": "=",
    "AsyncFor": "for",
    "AsyncFunctionDef": "function",
    "AsyncWith": "with",
    "AugAssignAdd": "+=",
    "Break": "break",
    "Call": "def",
    "ClassDef": "class",
    "Continue": "continue",
    "For": "for",
    "FunctionDef": "function",
    "If": "if",
    "Import": "import",
    "ImportFrom": "import",
    "Match": "match",
    "Pass": "pass",
    "Try": "try",
    "TryStar": "try",
    "While": "while",
    "With": "with",
}

PYTHON_KIND_MAP = {
    "Module": SemanticKind.TRANSLATION_UNIT,
    "FunctionDef": SemanticKind.FUNCTION,
    "AsyncFunctionDef": SemanticKind.FUNCTION,
    "ClassDef": SemanticKind.CLASS,
    "Call": SemanticKind.CALL,
    "Name": SemanticKind.NAME,
    "Attribute": SemanticKind.ATTRIBUTE,
    "arg": SemanticKind.PARAMETER,
    "Param": SemanticKind.PARAMETER,
    "Constant": SemanticKind.LITERAL,
    "Integer": SemanticKind.LITERAL,
    "Float": SemanticKind.LITERAL,
    "SimpleString": SemanticKind.LITERAL,
    "FormattedString": SemanticKind.LITERAL,
    "Assign": SemanticKind.ASSIGNMENT,
    "AnnAssign": SemanticKind.ASSIGNMENT,
    "AugAssign": SemanticKind.ASSIGNMENT,
    "NamedExpr": SemanticKind.ASSIGNMENT,
    "BinOp": SemanticKind.BINARY_OPERATION,
    "BinaryOperation": SemanticKind.BINARY_OPERATION,
    "BoolOp": SemanticKind.BINARY_OPERATION,
    "Compare": SemanticKind.BINARY_OPERATION,
    "UnaryOp": SemanticKind.UNARY_OPERATION,
    "UnaryOperation": SemanticKind.UNARY_OPERATION,
    "If": SemanticKind.CONDITIONAL,
    "IfExp": SemanticKind.CONDITIONAL,
    "For": SemanticKind.LOOP,
    "AsyncFor": SemanticKind.LOOP,
    "While": SemanticKind.LOOP,
    "Return": SemanticKind.RETURN,
    "Import": SemanticKind.IMPORT,
    "ImportFrom": SemanticKind.IMPORT,
    "Assert": SemanticKind.CONDITIONAL,
    "With": SemanticKind.LOOP,
    "AsyncWith": SemanticKind.LOOP,
    "Raise": SemanticKind.RETURN,
    "Break": SemanticKind.RETURN,
    "Continue": SemanticKind.RETURN,
    "Pass": SemanticKind.STATEMENT,
    "Try": SemanticKind.STATEMENT,
    "TryStar": SemanticKind.STATEMENT,
    "Delete": SemanticKind.STATEMENT,
    "Expr": SemanticKind.EXPRESSION,
    "Await": SemanticKind.EXPRESSION,
    "Yield": SemanticKind.EXPRESSION,
    "YieldFrom": SemanticKind.EXPRESSION,
}
