[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
[project]
name = "renaissance-experiments"
version = "0.3.0"
description = "Python version of the renaissance experiments"
readme = "README.md"
authors = [
    {name = "Luna Li", email = "luna.li@capgemini.com"}
]
license = {text = "MIT"}
requires-python = ">=3.12"
dependencies = [
    # List your dependecies here
    "textx",
    "dataclasses-json",
    "clang>=18.1.8",
    "libclang",
    "parameterized",
    "coverage",
    "pyperclip"
]



[[tool.poetry.source]]
name = "renai"
url = "https://github.com/TNO/Renaissance-Experiments"

[tool.poetry.dependencies]
python = "^3.12"

bandit = { version = "^1.6.2", optional = true }
behave = { version = "^1.2.6", optional = true }
black = { version = "^19.10b0", optional = true }
cohesion = { version = "^1.0.0", optional = true }
coverage-enable-subprocess = { version = "^1.0", optional = true }
mock = { version = "^4.0.1", optional = true }
nose = { version = "^1.3.7", optional = true }
pycodestyle = { version = "^2.5.0", optional = true }
pydocstyle = { version = "^5.0.2", optional = true }
pylint = { version = "^2.4.4", optional = true }
pytest = { version = "^5.3.5", optional = true }
radon = { version = "^4.1.0", optional = true }
vulture = { version = "^1.3", optional = true }
xenon = { version = "^0.7.0", optional = true }
coverage = {version = "^5.2.1", optional = true}
pyecore = "0.11.7"
pyyaml = "^5.3.1"

[tool.poetry.extras]
all = ["bandit", "behave", "black", "cohesion", "coverage", "coverage-enable-subprocess", "mock", "nose", "pycodestyle", "pydocstyle", "pylint", "pytest", "radon", "vulture", "xenon"]
bandit = ["bandit"]
black = ["black"]
cohesion = ["cohesion"]
pycodestyle = ["pycodestyle"]
pydocstyle = ["pydocstyle"]
pylint = ["pylint", "behave", "mock", "nose", "pytest"]
radon = ["radon", "xenon"]
vulture = ["vulture"]
pytest = ["pytest", "mock", "coverage"]
behave = ["behave", "coverage-enable-subprocess", "nose"]

[tool.poetry.urls]
issues = "https://github.com/TNO/Renaissance-Experiments"

[tool.poetry.scripts]
 model-model = "model_model.transformer:main"

[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"