Feature: taut migration
  Scenario: migrate taut to unittest without syntax errors
    Given 'targets/taut/taut_test.py' file
    And it contains 'import TAUT'
    And it contains 'class TestImport(TAUT.TestCase):'
    And it contains 'self.import_and_verify_module('ABCDxTL')'
    And it contains '@TAUT.log_stub'
    And it contains 'with TAUT.TestDoubles(abcdxtl=FakeABCDxTL(None)):'
    And it contains 'log = TAUT.Logger()'
    And it contains 'def setUp(self):'
    And it contains 'self.doubles'
    And it contains 'def tearDown(self):'
    And it contains 'self.tds'
    And it contains 'def setUpCommon(self):'
    And it contains 'def tearDownCommon(self):'
    And it contains 'def test_readout_is_ok(self):\n        self.doubles.append('
    And it contains 'def test_read_two_doubles(self):\n        self.doubles.append('
    And it contains 'self.assert_false'
    And it contains 'self.assert_true'
    And it contains 'self.assert_equal'
    And an AST extracted from that source file without errors
    When I convert taut to unittest
    Then AST extracted from that conversion should without errors
    And it should not contain 'import TAUT'
    And it should contain 'class TestImport(unittest.TestCase):'
    And it should contain 'import ABCDxTL\n        self.assertIsNotNone(ABCDxTL)'
    And it should not contain '@TAUT.log_stub'
    And it should contain 'fake_abcdxtl = FakeABCDxTL(None)'
    And it should not contain 'log = TAUT.Logger()'
    And it should contain 'test_log = fake_abcdxtl.create_test_log(test_log_id)'
    And it should contain 'test_log, version_mismatch = fake_abcdxtl.retrieve_test_log(file_id, test_log_id, file_name)'
    And it should contain 'fake_abcdxtl.store_test_log(file_id, test_log)'
    And it should contain 'self.patches'
    And it should contain 'p.start()'
    And it should not contain 'self.doubles'
    And it should contain 'self.patches'
    And it should contain 'p.stop()'
    And it should not contain 'self.tds'
    And it should contain 'def setUpCommon(self):'
    And it should contain 'self.patchers'
    And it should contain 'p.start()'
    And it should contain 'def tearDownCommon(self):'
    And it should contain 'self.patchers'
    And it should contain 'p.stop()'
    And it should contain 'def test_readout_is_ok(self):\n        with patch.object('
    And it should contain 'def test_read_two_doubles(self):\n        with patch.object('
    And it should contain 'self.assertFalse'
    And it should contain 'self.assertTrue'
    And it should contain 'self.assertEqual'